server:
  port: 8761

eureka:
  instance:
    # 与此实例相关联的主机名，是其他实例可以用来进行请求的准确名称
    hostname: localhost
    prefer-ip-address: true
    # 此实例注册到eureka服务端的唯一的实例ID,其组成为${spring.application.name}:${spring.application.instance_id:${random.value}}
    instance-id: ${spring.application.name}:${eureka.instance.ip-address:${spring.cloud.client.ip-address}}:${server.port}
    # eureka客户需要多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30 秒
    lease-renewal-interval-in-seconds: 10
    # Eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认为90秒
    lease-expiration-duration-in-seconds: 15
  server:
    # 自我保护模式，当出现出现网络分区、eureka在短时间内丢失过多客户端时，会进入自我保护模式，即一个服务长时间没有发送心跳，eureka也不会将其删除，默认为true
    enable-self-preservation: false
    # 过期实例应该启动并运行的时间间隔，单位为毫秒，默认为60 * 1000
    eviction-interval-timer-in-ms: 10000
  client:
    # 实例是否在eureka服务器上注册自己的信息以供其他服务发现，默认为true
    registerWithEureka: false
    # 此客户端是否获取eureka服务器注册表上的注册信息，默认为true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    # 从eureka服务器注册表中获取注册信息的时间间隔（s），默认为30秒
    registry-fetch-interval-seconds: 30
    # 复制实例变化信息到eureka服务器所需要的时间间隔（s），默认为30秒
    instance-info-replication-interval-seconds: 30
    # 最初复制实例信息到eureka服务器所需的时间（s），默认为40秒
    initial-instance-info-replication-interval-seconds: 40
    # 获取eureka服务的代理主机，默认为null
    # proxy-host:
    # 获取eureka服务的代理端口, 默认为null
    # proxy-port:
    # 获取eureka服务的代理用户名，默认为null
    # proxy-user-name:
    # 获取eureka服务的代理密码，默认为null
    # proxy-password:
    # eureka注册表的内容是否被压缩，默认为true，并且是在最好的网络流量下被压缩
    g-zip-content: true
    # eureka需要超时读取之前需要等待的时间，默认为8秒
    eureka-server-read-timeout-seconds: 8
    # eureka需要超时连接之前需要等待的时间，默认为5秒
    eureka-server-connect-timeout-seconds: 5
    # 获取实现了eureka客户端在第一次启动时读取注册表的信息作为回退选项的实现名称
    # backup-registry-impl:
    # eureka客户端允许所有eureka服务器连接的总数目，默认是200
    eureka-server-total-connections: 200
    # eureka客户端允许eureka服务器主机连接的总数目，默认是50
    eureka-server-total-connections-per-host: 50
    # 表示eureka注册中心的路径，如果配置为eureka，则为http://x.x.x.x:x/eureka/，在eureka的配置文件中加入此配置表示eureka作为客户端向注册中心注册，从而构成eureka集群。此配置只有在eureka服务器ip地址列表是在DNS中才会用到，默认为null
    # eureka-server-u-r-l-context: eureka
    # 获取eureka服务器的端口，此配置只有在eureka服务器ip地址列表是在DNS中才会用到。默认为null
    # eureka-server-port:
    # 获取要查询的DNS名称来获得eureka服务器，此配置只有在eureka服务器ip地址列表是在DNS中才会用到。默认为null
    # eureka-server-d-n-s-name:
    # eureka客户端是否应该使用DNS机制来获取eureka服务器的地址列表，默认为false
    # use-dns-for-fetching-service-urls: false

spring:
  application:
    name: sky-eureka
  cloud:
    inetutils:
      ## 设置网络超时
      timeout-seconds: 5
      ## 忽略网卡
      ignored-interfaces:
        - VMware Virtual Ethernet Adapter for VMnet1
        - VMware Virtual Ethernet Adapter for VMnet8
        - VirtualBox Host-Only Ethernet Adapter