# 端口号
server:
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /
  port: 8090
  # gzip
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/css,application/javascript,text/xml,text/plain
    # 超过2kb就压缩
    min-response-size: 2048

# spring配置
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
  application:
    name: garden-system
  profiles:
    active: dev

  jackson:
    serialization:
      write-dates-as-timestamps: true

  servlet:
    # 文件上传大小配置
    multipart:
      # 最大请求大小
      max-request-size: 100MB
      # 最大文件大小
      max-file-size: 50MB

# nacos
#nacos:
#  config:
#    server-addr: 127.0.0.1:8848