# spring配置
spring:
  # mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/garden?useUnicode=true&characterEncoding=utf-8&useSSL=true&allowMultiQueries=true
    username: garden
    password: 123456
    #druid
    type: com.zaxxer.hikari.HikariDataSource

  # redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）默认是2000ms
    timeout: 2000ms

  mvc:
    # 设置静态文件路径，js,css等
    static-path-pattern: /static/**


  resources:
    static-locations: file:D:/images/

  # 配置freemarker
  freemarker:
    # 设置模板后缀名
    suffix: .ftl
    # 设置文档类型
    content-type: text/html; charset=utf-8
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存
    cache: false
    # 设置ftl文件路径
    template-loader-path:
      - classpath:/templates/
    check-template-location: true
    expose-request-attributes: true
    # 当templates需要从多个jar里面获取的时候，设置为false
    prefer-file-system-access: false

# mybatis
mybatis:
  typeAliasesPackage: com.stream.garden.*.*.dao
  mapperLocations:
    - classpath*:com/stream/garden/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  # id自动生成
  keyGenMode: SNOW

# pagehelper分页
pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# log配置
#logging:
#  file: /logs/${spring.application.name}.log
#  level:
#    ROOT: error
#    com.stream.garden.framework.jdbc: error
#    com.stream.garden: debug
#    org.mybatis: debug

# garden
garden:
  name: garden
  password: 123456
  excludePath:
    - /favicon.ico
    - /static/**
    - /verifyCode
    - /safetyCheck
  login-path: /login
  safetyType: normal
  path: /adsfsdf/asdfas/asdf
  upload-path: /www/garden
  upload-dir: /adsfsdf/asdfas/asdf
  jwt:
    clientId: 6AF45DE098AA4E9FA84034793F8673CD
    base64Secret: NkFGNDVERTA5OEFBNEU5RkE4NDAzNDc5M0Y4NjczQ0Q=
    name: garden_api_user
    expiresSecond: 172800

  # 限流配置
  limit:
    limit-rule: APPLICATION
    # limit-rule: NONE
    # 1s
    period: 1
    # 10次
    count: 10

  # 任务调度
  job:
    enabled: true
