# 端口号
server:
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /
  port: 8090
  # gzip
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/css,application/javascript,text/xml,text/plain
    # 超过2kb就压缩
    min-response-size: 2048

# spring配置
spring:
  messages:
    encoding: UTF-8
  application:
    name: springboot230
